# Label Encoding
* Assign a each category unique no
* Used for ordinal or no ordered data
* It may imply order to the nominal data

In [1]:
from sklearn.preprocessing import LabelEncoder
import pandas as pd

In [3]:
data  = {'color':['Red','Blue',"Green","Yellow"]}
df = pd.DataFrame(data)

In [5]:
df

    color
0     Red
1    Blue
2   Green
3  Yellow

In [7]:
le = LabelEncoder()
df['Encoded_age'] = le.fit_transform(df[['color']])

/home/abdullah/anaconda3/lib/python3.11/site-packages/sklearn/preprocessing/_label.py:116: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)

In [8]:
df

    color  Encoded_age
0     Red            2
1    Blue            0
2   Green            1
3  Yellow            3