## ordinal Encoding

In [1]:
from sklearn.preprocessing import OrdinalEncoder
import pandas as pd

In [16]:
data ={
    'Education_Level': ['High School', 'PhD', 'Master', 'Bachelor']
    }
df = pd.DataFrame(data)

In [17]:
df

  Education_Level
0     High School
1             PhD
2          Master
3        Bachelor

In [19]:
encoder = OrdinalEncoder(
    categories=[['High School', 'Bachelor', 'Master', 'PhD']])
df['Level_Encoded'] = encoder.fit_transform(df[['Education_Level']])

In [20]:
df

  Education_Level  Level_Encoded
0     High School            0.0
1             PhD            3.0
2          Master            2.0
3        Bachelor            1.0